import { describe, it, expect } from 'bun:test'
import { sessionLabel, fmt, fmtCost, fmtCostFull, fmtElapsed } from './format'

describe('fmtCost', () => {
  // A local model (see isLocalModelId/LOCAL_MODEL_PRICE in local-models.ts) prices at exactly 0 —
  // that fact must be visible, not collapsed into the same '<R$0,05' label a real sub-cent
  // proprietary call gets. Otherwise a free Ollama session and a genuinely (if tiny) billed one
  // are indistinguishable in every cost breakdown, which is the one place a user could tell them apart.
  it('renders exact zero as a real zero in BRL, not the sub-cent placeholder', () => {
    expect(fmtCost(0, 'BRL', 5.5)).toBe('R$0,00')
  })

  it('still uses the sub-cent placeholder for a genuinely tiny nonzero BRL amount', () => {
    expect(fmtCost(0.001, 'BRL', 5.5)).toBe('<R$0,05')
  })

  it('renders exact zero as a real zero in USD', () => {
    expect(fmtCost(0, 'USD')).toBe('USD 0.00')
  })

  it('still uses the sub-cent placeholder for a genuinely tiny nonzero USD amount', () => {
    expect(fmtCost(0.0001, 'USD')).toBe('<USD 0.01')
  })

  it('formats a normal BRL amount with thousands separators', () => {
    expect(fmtCost(1000, 'BRL', 5.5)).toBe('R$5.500,00')
  })
})

describe('fmtCostFull', () => {
  it('renders exact zero as a real zero, not the sub-cent placeholder', () => {
    expect(fmtCostFull(0, 'BRL', 5.5)).toBe('R$0,000000')
    expect(fmtCostFull(0, 'USD')).toBe('USD 0.000000')
  })
})

describe('sessionLabel', () => {
  it('prefers the title when present', () => {
    expect(sessionLabel({ title: 'Fix login bug', first_prompt: 'whatever' })).toBe('Fix login bug')
  })

  it('trims the title', () => {
    expect(sessionLabel({ title: '  Spaced title  ' })).toBe('Spaced title')
  })

  it('falls back to the first prompt when there is no title', () => {
    expect(sessionLabel({ first_prompt: 'Refactor the parser' })).toBe('Refactor the parser')
  })

  it('strips local-command-caveat wrappers from the first-prompt fallback', () => {
    const fp = '<local-command-caveat>Caveat: generated by a local command. DO NOT respond</local-command-caveat>'
    expect(sessionLabel({ first_prompt: fp })).toBe('')
  })

  it('strips command-name wrappers and keeps the readable remainder', () => {
    const fp = '<command-name>/commit</command-name> please commit my work'
    expect(sessionLabel({ first_prompt: fp })).toBe('please commit my work')
  })

  it('collapses whitespace left behind by stripped tags', () => {
    const fp = '<command-message>x</command-message>   real    text'
    expect(sessionLabel({ first_prompt: fp })).toBe('real text')
  })

  it('returns an empty string when nothing usable is present', () => {
    expect(sessionLabel({})).toBe('')
    expect(sessionLabel({ title: '   ', first_prompt: '' })).toBe('')
  })
})

describe('fmtElapsed', () => {
  it('reads as "under a minute" below one minute, in both languages', () => {
    expect(fmtElapsed(0, 'en')).toBe('<1m')
    expect(fmtElapsed(0, 'pt')).toBe('<1min')
    expect(fmtElapsed(30_000, 'en')).toBe('<1m')
    expect(fmtElapsed(30_000, 'pt')).toBe('<1min')
  })

  it('shows minutes alone under an hour', () => {
    expect(fmtElapsed(45 * 60_000, 'en')).toBe('45m')
    expect(fmtElapsed(45 * 60_000, 'pt')).toBe('45min')
  })

  it('shows hours and minutes under a day, dropping the minutes when zero', () => {
    expect(fmtElapsed(62 * 60_000, 'en')).toBe('1h 2m')
    expect(fmtElapsed(62 * 60_000, 'pt')).toBe('1h 2min')
    expect(fmtElapsed(3 * 3_600_000, 'en')).toBe('3h')
    expect(fmtElapsed(3 * 3_600_000, 'pt')).toBe('3h')
  })

  it('shows days and hours at or beyond a day, dropping the hours when zero', () => {
    expect(fmtElapsed(25 * 3_600_000, 'en')).toBe('1d 1h')
    expect(fmtElapsed(25 * 3_600_000, 'pt')).toBe('1d 1h')
    expect(fmtElapsed(48 * 3_600_000, 'en')).toBe('2d')
    expect(fmtElapsed(48 * 3_600_000, 'pt')).toBe('2d')
  })

  it('is null for negative or non-finite spans — bad data, never a confident duration', () => {
    expect(fmtElapsed(-1, 'en')).toBeNull()
    expect(fmtElapsed(NaN, 'en')).toBeNull()
    expect(fmtElapsed(Infinity, 'en')).toBeNull()
  })
})

describe('fmt', () => {
  it('formats thousands with K', () => {
    expect(fmt(1_500)).toBe('1.5K')
  })

  it('formats millions with M', () => {
    expect(fmt(2_400_000)).toBe('2.4M')
  })

  it('formats billions with B rather than four-digit millions', () => {
    // 13_290_800_000 used to render as "13290.8M", which is unreadable at a glance.
    expect(fmt(13_290_800_000)).toBe('13.3B')
  })

  it('formats trillions with T', () => {
    expect(fmt(2_500_000_000_000)).toBe('2.5T')
  })

  it('leaves small numbers alone', () => {
    expect(fmt(942)).toBe('942')
  })
})
