/** Words for the personal vault page (`/vault`), EN + PT, one table (`personalText.test.ts` walks it). */
export type PLang = 'en' | 'pt'
type Pair = { en: string; pt: string }

export const PERSONAL_TEXT = {
  title: { en: 'Vault', pt: 'Cofre' },
  intro: {
    en: 'Your own passwords, logins, API keys and notes, encrypted on this computer. The list shows names only; seeing a value asks you to confirm every time.',
    pt: 'As suas senhas, logins, chaves de API e anotações, criptografados neste computador. A lista mostra só os nomes; ver um valor pede a sua confirmação toda vez.',
  },
  new: { en: 'New secret', pt: 'Novo segredo' },
  importEnv: { en: 'Import .env', pt: 'Importar .env' },
  groups: { en: 'Groups', pt: 'Grupos' },
  newGroup: { en: 'New group', pt: 'Novo grupo' },
  search: { en: 'Search by name, group, tag or note…', pt: 'Buscar por nome, grupo, tag ou anotação…' },
  allKinds: { en: 'All kinds', pt: 'Todos os tipos' },
  allGroups: { en: 'All groups', pt: 'Todos os grupos' },
  noGroup: { en: 'No group', pt: 'Sem grupo' },
  trash: { en: 'Trash', pt: 'Lixeira' },
  trashNote: { en: 'Items stay here for 30 days, then they are deleted for good.', pt: 'Os itens ficam aqui por 30 dias e depois são apagados de vez.' },
  empty: { en: 'Nothing here yet. Add your first secret.', pt: 'Nada aqui ainda. Adicione o seu primeiro segredo.' },
  noMatch: { en: 'Nothing matches this search.', pt: 'Nada corresponde a esta busca.' },
  showing: { en: '{a}–{b} of {n}', pt: '{a}–{b} de {n}' },
  perPage: { en: 'per page', pt: 'por página' },
  prev: { en: 'Previous', pt: 'Anterior' },
  next: { en: 'Next', pt: 'Próxima' },
  locked: { en: 'The vault is locked. Open it in Settings → Vault, then come back.', pt: 'O cofre está trancado. Abra-o em Ajustes → Cofre e volte aqui.' },
  openSettings: { en: 'Open Settings → Vault', pt: 'Abrir Ajustes → Cofre' },
  needsCode: { en: 'Type the code from your authenticator to see the list.', pt: 'Digite o código do seu autenticador para ver a lista.' },
  codeLabel: { en: 'Authenticator code', pt: 'Código do autenticador' },
  confirm: { en: 'Confirm', pt: 'Confirmar' },
  cancel: { en: 'Cancel', pt: 'Cancelar' },
  save: { en: 'Save', pt: 'Salvar' },
  close: { en: 'Close', pt: 'Fechar' },
  working: { en: 'Working…', pt: 'Trabalhando…' },
  confirmHello: { en: 'Confirm on this computer (Windows Hello)…', pt: 'Confirme neste computador (Windows Hello)…' },
  reveal: { en: 'Show', pt: 'Ver' },
  hide: { en: 'Hide', pt: 'Ocultar' },
  copy: { en: 'Copy', pt: 'Copiar' },
  copied: { en: 'Copied — the clipboard is cleared in 30 s.', pt: 'Copiado — a área de transferência é limpa em 30 s.' },
  clipboardWarn: {
    en: 'While it is there, any program on this computer can read the clipboard, and a clipboard-history tool keeps it longer.',
    pt: 'Enquanto estiver lá, qualquer programa deste computador pode ler a área de transferência, e um histórico de área de transferência guarda por mais tempo.',
  },
  edit: { en: 'Edit', pt: 'Editar' },
  versions: { en: 'Versions', pt: 'Versões' },
  delete: { en: 'Move to trash', pt: 'Mover para a lixeira' },
  restore: { en: 'Restore', pt: 'Restaurar' },
  purge: { en: 'Delete for good', pt: 'Apagar de vez' },
  purgeConfirm: { en: 'Delete "{name}" for good? Its versions go too. This cannot be undone.', pt: 'Apagar "{name}" de vez? As versões vão junto. Não dá para desfazer.' },
  move: { en: 'Group', pt: 'Grupo' },
  kind_password: { en: 'Password', pt: 'Senha' },
  kind_login: { en: 'Login', pt: 'Login' },
  'kind_api-key': { en: 'API key', pt: 'Chave de API' },
  kind_env: { en: '.env', pt: '.env' },
  kind_note: { en: 'Note', pt: 'Anotação' },
  field_login: { en: 'Login', pt: 'Login' },
  field_password: { en: 'Password', pt: 'Senha' },
  field_value: { en: 'Value', pt: 'Valor' },
  loginHint: { en: 'e-mail, username, phone, ID…', pt: 'e-mail, usuário, telefone, CPF…' },
  f_kind: { en: 'Kind', pt: 'Tipo' },
  f_name: { en: 'Name', pt: 'Nome' },
  f_url: { en: 'Site / URL (optional)', pt: 'Site / URL (opcional)' },
  f_group: { en: 'Group', pt: 'Grupo' },
  f_tags: { en: 'Tags (comma-separated)', pt: 'Tags (separadas por vírgula)' },
  f_notes: { en: 'Notes / context', pt: 'Anotações / contexto' },
  f_keep: { en: 'Leave empty to keep the current value.', pt: 'Deixe vazio para manter o valor atual.' },
  editAsks: { en: 'Saving asks you to confirm (Windows Hello).', pt: 'Salvar pede a sua confirmação (Windows Hello).' },
  createTitle: { en: 'New secret', pt: 'Novo segredo' },
  editTitle: { en: 'Edit secret', pt: 'Editar segredo' },
  versionsTitle: { en: 'Versions of "{name}"', pt: 'Versões de "{name}"' },
  versionsNote: { en: 'The last 10 versions are kept. Restoring one asks for your code and Windows Hello, and becomes the newest.', pt: 'As últimas 10 versões ficam guardadas. Restaurar uma pede o seu código e o Windows Hello, e ela vira a mais nova.' },
  version: { en: 'v{n}', pt: 'v{n}' },
  current: { en: 'current', pt: 'atual' },
  restoreThis: { en: 'Restore this one', pt: 'Restaurar esta' },
  updated: { en: 'Updated {date}', pt: 'Atualizado em {date}' },
  importTitle: { en: 'Import a .env file', pt: 'Importar um arquivo .env' },
  importIntro: {
    en: 'Each KEY=value becomes its own secret. You review the keys first — the values stay hidden — and the file itself is never stored.',
    pt: 'Cada CHAVE=valor vira um segredo próprio. Você revisa as chaves antes — os valores ficam ocultos — e o arquivo em si nunca é guardado.',
  },
  chooseFile: { en: 'Choose a .env file', pt: 'Escolher um arquivo .env' },
  importSkipped: { en: '{n} line(s) were not KEY=value and were ignored.', pt: '{n} linha(s) não eram CHAVE=valor e foram ignoradas.' },
  act_import: { en: 'Import', pt: 'Importar' },
  act_skip: { en: 'Skip', pt: 'Pular' },
  act_replace: { en: 'Replace (new version)', pt: 'Substituir (nova versão)' },
  act_rename: { en: 'Import with another name', pt: 'Importar com outro nome' },
  clash: { en: 'already exists', pt: 'já existe' },
  emptyValue: { en: 'empty', pt: 'vazio' },
  importInto: { en: 'Into group', pt: 'No grupo' },
  importGo: { en: 'Import', pt: 'Importar' },
  importDone: { en: '{c} created, {r} replaced, {s} skipped.', pt: '{c} criados, {r} substituídos, {s} pulados.' },
  groupName: { en: 'Group name (a folder, a repo, a project…)', pt: 'Nome do grupo (uma pasta, um repositório, um projeto…)' },
  rename: { en: 'Rename', pt: 'Renomear' },
  deleteGroup: { en: 'Delete group', pt: 'Apagar grupo' },
  deleteGroupNote: { en: 'Its secrets are kept and move out of the group.', pt: 'Os segredos dele são mantidos e saem do grupo.' },
  items: { en: '{n} secret(s)', pt: '{n} segredo(s)' },
  network: { en: 'Could not reach agentop on this computer.', pt: 'Não foi possível falar com o agentop neste computador.' },
  neverPaste: { en: 'Agentistics never asks you to paste a secret into a chat.', pt: 'O Agentistics nunca pede para você colar um segredo num chat.' },
  backupNote: {
    en: 'Backups keep older encrypted copies of your vault; they are erased by themselves after a key change, or now, with this button.',
    pt: 'Os backups guardam cópias criptografadas antigas do seu cofre; elas são apagadas sozinhas depois de uma troca de chave, ou agora, por este botão.',
  },
  backupWipe: { en: 'Erase the vault\'s history in the backup', pt: 'Apagar o histórico do cofre no backup' },
  backupWipeConfirm: {
    en: 'Erase the older vault copies from the GitHub backup? The newest stays; this cannot be undone. It asks for your code and Windows Hello.',
    pt: 'Apagar as cópias antigas do cofre do backup no GitHub? A mais nova fica; não dá para desfazer. Pede o seu código e o Windows Hello.',
  },
  backupWiped: { en: '{n} older vault copy(ies) erased from the backup.', pt: '{n} cópia(s) antiga(s) do cofre apagada(s) do backup.' },
  phoneTitle: { en: 'On your phone', pt: 'No celular' },
  phoneInsecure: {
    en: 'To use your phone\'s fingerprint or face, open Agentistics by its https address — for example by turning on HTTPS certificates in your Tailscale network and using the machine\'s https name.',
    pt: 'Para usar a digital ou o rosto do celular, abra o Agentistics pelo endereço https — por exemplo ligando os certificados HTTPS na sua rede Tailscale e usando o nome https da máquina.',
  },
  phoneUnsupported: { en: 'This browser cannot use a passkey.', pt: 'Este navegador não consegue usar uma passkey.' },
  phoneReady: { en: 'This phone is registered: it opens the vault with its fingerprint or face plus your code, and seeing or changing a secret asks for its fingerprint again.', pt: 'Este celular está registrado: abre o cofre com a digital ou o rosto mais o seu código, e ver ou mudar um segredo pede a digital de novo.' },
  phoneRegisterWhy: {
    en: 'Register this phone so it can open the vault and see secrets with its own fingerprint or face. It asks your code here, then an approval with Windows Hello on the computer — once.',
    pt: 'Registre este celular para ele abrir o cofre e ver segredos com a própria digital ou rosto. Pede o seu código aqui e depois uma aprovação com o Windows Hello no computador — uma vez só.',
  },

  phoneRegister: { en: 'Register this phone\'s fingerprint', pt: 'Registrar a digital deste celular' },
  phoneLabel: { en: 'Phone', pt: 'Celular' },
  phoneApproveOnPc: { en: 'Approve it in Windows Hello on the computer…', pt: 'Aprove no Windows Hello do computador…' },
  phoneCodeOn: { en: 'The computer also accepts your code here: a fresh code opens 30 seconds to see secrets.', pt: 'O computador também aceita o seu código aqui: um código novo abre 30 segundos para ver segredos.' },
  phoneDesktopIntro: {
    en: 'Phones that can open the vault and its secrets. A phone registers from the phone itself: it asks your code there, and a request appears here for you to approve with Windows Hello. Windows Hello is never asked from a phone.',
    pt: 'Celulares que podem abrir o cofre e os segredos. Um celular se registra pelo próprio celular: ele pede o seu código lá, e aparece um pedido aqui para você aprovar com o Windows Hello. O Windows Hello nunca é pedido a partir de um celular.',
  },

  phoneNone: { en: 'No phone registered yet.', pt: 'Nenhum celular registrado ainda.' },
  phoneRemove: { en: 'Remove', pt: 'Remover' },
  phoneCodeToggle: { en: 'Open the vault from the phone with the code alone (and see secrets for 30 s)', pt: 'Abrir o cofre pelo celular só com o código (e ver segredos por 30 s)' },
  phoneCodeCost: {
    en: 'Off by default. With it on, a phone you approved here once keeps a key of its own, and that phone plus your current code opens the vault (and shows secrets for 30 seconds) — no fingerprint. A code alone, on any other device, still opens nothing. Turning it off deletes every such key at once. Over plain http outside Tailscale the code travels unencrypted. Editing and deleting still need the phone\'s fingerprint.',
    pt: 'Desligado por padrão. Ligado, um celular que você aprovou aqui uma vez guarda uma chave própria, e esse celular mais o seu código atual abre o cofre (e mostra segredos por 30 segundos) — sem digital. Um código sozinho, em qualquer outro aparelho, continua não abrindo nada. Desligar apaga todas essas chaves de uma vez. Em http simples fora do Tailscale o código passa sem criptografia. Editar e apagar continuam pedindo a digital do celular.',
  },
  phoneDevices: { en: 'Phones that open with the code alone', pt: 'Celulares que abrem só com o código' },
  phoneStale: { en: '{n} phone key(s) stopped working when the vault changed its key; those phones must be approved again.', pt: '{n} chave(s) de celular pararam de funcionar quando o cofre trocou de chave; esses celulares precisam ser aprovados de novo.' },
  phoneStaleClear: { en: 'Clear them', pt: 'Limpar' },
  phonePasskeys: { en: 'Phones with biometrics', pt: 'Celulares com digital' },

} as const satisfies Record<string, Pair>

export type PKey = keyof typeof PERSONAL_TEXT
export function pt_(k: PKey, lang: PLang, vars: Record<string, string | number> = {}): string {
  return PERSONAL_TEXT[k][lang].replace(/\{(\w+)\}/g, (_, v: string) => String(vars[v] ?? `{${v}}`))
}
