/** Words for the personal vault page (`/vault`), EN + PT, one table (`personalText.test.ts` walks it). */
export type PLang = 'en' | 'pt'
type Pair = { en: string; pt: string }

export const PERSONAL_TEXT = {
  title: { en: 'Vault', pt: 'Cofre' },
  intro: {
    en: 'Your own passwords, logins, API keys and notes, encrypted on this computer. The list shows names only; seeing a value asks you to confirm every time.',
    pt: 'As suas senhas, logins, chaves de API e anotações, criptografados neste computador. A lista mostra só os nomes; ver um valor pede a sua confirmação toda vez.',
  },
  new: { en: 'New secret', pt: 'Novo segredo' },
  importEnv: { en: 'Import .env', pt: 'Importar .env' },
  groups: { en: 'Groups', pt: 'Grupos' },
  newGroup: { en: 'New group', pt: 'Novo grupo' },
  createGroupRow: { en: 'Create group “{text}”', pt: 'Criar grupo “{text}”' },
  searchOrCreateGroup: { en: 'Type to search or create…', pt: 'Digite para buscar ou criar…' },
  groupCreated: { en: 'Group “{name}” created.', pt: 'Grupo “{name}” criado.' },
  importKindLabel: { en: 'Kind', pt: 'Tipo' },
  markAllApiKey: { en: 'Mark all as API key', pt: 'Marcar todos como chave de API' },
  unmarkAllApiKey: { en: 'Back to .env for all', pt: 'Voltar todos para .env' },
  importKindNote: { en: 'API keys are “use only”: sessions use them, nobody sees or copies the value.', pt: 'Chaves de API são “só uso”: as sessões usam, ninguém vê nem copia o valor.' },
  createTypeRow: { en: 'Create type…', pt: 'Criar tipo…' },
  typeDialogTitle: { en: 'New type', pt: 'Novo tipo' },
  typeName: { en: 'Type name', pt: 'Nome do tipo' },
  typeNamePh: { en: 'e.g. Mongo token', pt: 'ex.: Token do Mongo' },
  typeBase: { en: 'Based on', pt: 'Baseado em' },
  typeBaseHelp: { en: 'The base kind decides the fields and whether the value is “use only”. The name is only your label.', pt: 'O tipo base define os campos e se o valor é “só uso”. O nome é só o seu rótulo.' },
  typeSave: { en: 'Create type', pt: 'Criar tipo' },
  typeEmpty: { en: 'Give the type a name.', pt: 'Dê um nome ao tipo.' },
  typeLong: { en: 'Up to 40 characters.', pt: 'No máximo 40 caracteres.' },
  typeTaken: { en: 'You already have a type with that name.', pt: 'Você já tem um tipo com esse nome.' },
  typeFull: { en: 'The limit of 30 types was reached.', pt: 'O limite de 30 tipos foi atingido.' },
  typesTitle: { en: 'Custom types', pt: 'Tipos personalizados' },
  typesNone: { en: 'No custom types yet. Create one from the kind field of a secret or of an import.', pt: 'Nenhum tipo personalizado ainda. Crie um no campo de tipo de um segredo ou de uma importação.' },
  typesDesc: { en: 'Your own names for kinds. A secret keeps its base kind; removing a type only removes the name.', pt: 'Seus nomes para os tipos. O segredo mantém o tipo base; remover um tipo só remove o nome.' },
  typeRemove: { en: 'Remove type', pt: 'Remover tipo' },
  typeRemoveConfirm: { en: 'Remove the type “{name}”? Secrets that use it go back to their base kind; nothing else changes.', pt: 'Remover o tipo “{name}”? Os segredos que o usam voltam ao tipo base; nada mais muda.' },
  typeRename: { en: 'Rename type', pt: 'Renomear tipo' },
  selectMode: { en: 'Select', pt: 'Selecionar' },
  selectModeTitle: { en: 'Tick several secrets to delete them together', pt: 'Marque vários segredos para excluí-los juntos' },
  selectRow: { en: 'Select this secret', pt: 'Selecionar este segredo' },
  selectAll: { en: 'Select all ({n})', pt: 'Selecionar todos ({n})' },
  deleteN: { en: 'Delete ({n})', pt: 'Excluir ({n})' },
  doneSelecting: { en: 'Done', pt: 'Concluir' },
  batchTitle: { en: 'Delete {n} secrets?', pt: 'Excluir {n} segredos?' },
  batchMessage: { en: 'They go to the Trash for 30 days and can be restored. You confirm once for all of them: {names}', pt: 'Vão para a Lixeira por 30 dias e podem ser restaurados. Você confirma uma vez para todos: {names}' },
  batchDone: { en: '{n} secrets moved to the Trash.', pt: '{n} segredos enviados para a Lixeira.' },
  batchPartial: { en: '{ok} moved to the Trash, {bad} failed: {names}', pt: '{ok} enviados para a Lixeira, {bad} falharam: {names}' },
  openRow: { en: 'Show details', pt: 'Ver detalhes' },
  closeRow: { en: 'Hide details', pt: 'Ocultar detalhes' },
  search: { en: 'Search by name, group, tag or note…', pt: 'Buscar por nome, grupo, tag ou anotação…' },
  allKinds: { en: 'All kinds', pt: 'Todos os tipos' },
  allGroups: { en: 'All groups', pt: 'Todos os grupos' },
  noGroup: { en: 'No group', pt: 'Sem grupo' },
  trash: { en: 'Trash', pt: 'Lixeira' },
  trashNote: { en: 'Items stay here for 30 days, then they are deleted for good.', pt: 'Os itens ficam aqui por 30 dias e depois são apagados de vez.' },
  empty: { en: 'Nothing here yet. Add your first secret.', pt: 'Nada aqui ainda. Adicione o seu primeiro segredo.' },
  noMatch: { en: 'Nothing matches this search.', pt: 'Nada corresponde a esta busca.' },
  showing: { en: '{a}–{b} of {n}', pt: '{a}–{b} de {n}' },
  perPage: { en: 'per page', pt: 'por página' },
  prev: { en: 'Previous', pt: 'Anterior' },
  next: { en: 'Next', pt: 'Próxima' },
  needsCode: { en: 'Type the code from your authenticator to see the list.', pt: 'Digite o código do seu autenticador para ver a lista.' },
  codeLabel: { en: 'Authenticator code', pt: 'Código do autenticador' },
  confirm: { en: 'Confirm', pt: 'Confirmar' },
  cancel: { en: 'Cancel', pt: 'Cancelar' },
  save: { en: 'Save', pt: 'Salvar' },
  close: { en: 'Close', pt: 'Fechar' },
  working: { en: 'Working…', pt: 'Trabalhando…' },
  confirmHello: { en: 'Confirm on this computer (Windows Hello)…', pt: 'Confirme neste computador (Windows Hello)…' },
  reveal: { en: 'Show', pt: 'Ver' },
  hide: { en: 'Hide', pt: 'Ocultar' },
  copy: { en: 'Copy', pt: 'Copiar' },
  copied: { en: 'Copied — the clipboard is cleared in 30 s.', pt: 'Copiado — a área de transferência é limpa em 30 s.' },
  clipboardWarn: {
    en: 'While it is there, any program on this computer can read the clipboard, and a clipboard-history tool keeps it longer.',
    pt: 'Enquanto estiver lá, qualquer programa deste computador pode ler a área de transferência, e um histórico de área de transferência guarda por mais tempo.',
  },
  edit: { en: 'Edit', pt: 'Editar' },
  versions: { en: 'Versions', pt: 'Versões' },
  delete: { en: 'Move to trash', pt: 'Mover para a lixeira' },
  restore: { en: 'Restore', pt: 'Restaurar' },
  purge: { en: 'Delete for good', pt: 'Apagar de vez' },
  purgeConfirm: { en: 'Delete "{name}" for good? Its versions go too. This cannot be undone.', pt: 'Apagar "{name}" de vez? As versões vão junto. Não dá para desfazer.' },
  move: { en: 'Group', pt: 'Grupo' },
  kind_password: { en: 'Password', pt: 'Senha' },
  kind_login: { en: 'Login', pt: 'Login' },
  'kind_api-key': { en: 'API key', pt: 'Chave de API' },
  kind_env: { en: '.env', pt: '.env' },
  kind_note: { en: 'Note', pt: 'Anotação' },
  field_login: { en: 'Login', pt: 'Login' },
  field_password: { en: 'Password', pt: 'Senha' },
  field_value: { en: 'Value', pt: 'Valor' },
  loginHint: { en: 'e-mail, username, phone, ID…', pt: 'e-mail, usuário, telefone, CPF…' },
  f_kind: { en: 'Kind', pt: 'Tipo' },
  f_name: { en: 'Name', pt: 'Nome' },
  f_url: { en: 'Site / URL (optional)', pt: 'Site / URL (opcional)' },
  f_group: { en: 'Group', pt: 'Grupo' },
  f_tags: { en: 'Tags (comma-separated)', pt: 'Tags (separadas por vírgula)' },
  f_notes: { en: 'Notes / context', pt: 'Anotações / contexto' },
  confirmEach: { en: 'Always confirm', pt: 'Sempre confirmar' },
  confirmEachHelp: { en: 'Ask Windows Hello (or your phone\'s biometrics) on every reveal and every send to a session, even with the vault open. Turning it off needs Hello once.', pt: 'Pede o Windows Hello (ou a biometria do celular) a cada revelação e a cada envio a uma sessão, mesmo com o cofre aberto. Para desligar, é preciso confirmar com o Hello.' },
  confirmEachOff: { en: 'no prompt', pt: 'sem confirmação' },
  f_keep: { en: 'Leave empty to keep the current value.', pt: 'Deixe vazio para manter o valor atual.' },
  editAsks: { en: 'Saving asks you to confirm (Windows Hello).', pt: 'Salvar pede a sua confirmação (Windows Hello).' },
  createTitle: { en: 'New secret', pt: 'Novo segredo' },
  editTitle: { en: 'Edit secret', pt: 'Editar segredo' },
  versionsTitle: { en: 'Versions of "{name}"', pt: 'Versões de "{name}"' },
  versionsNote: { en: 'The last 10 versions are kept. Restoring one asks for your code and Windows Hello, and becomes the newest.', pt: 'As últimas 10 versões ficam guardadas. Restaurar uma pede o seu código e o Windows Hello, e ela vira a mais nova.' },
  version: { en: 'v{n}', pt: 'v{n}' },
  current: { en: 'current', pt: 'atual' },
  restoreThis: { en: 'Restore this one', pt: 'Restaurar esta' },
  updated: { en: 'Updated {date}', pt: 'Atualizado em {date}' },
  importTitle: { en: 'Import a .env or JSON file', pt: 'Importar um arquivo .env ou JSON' },
  importIntro: {
    en: 'Each KEY=value of a .env file — or each "key": "value" of a flat JSON object — becomes its own secret. You review the keys first — the values stay hidden — and the file itself is never stored.',
    pt: 'Cada CHAVE=valor de um arquivo .env — ou cada "chave": "valor" de um objeto JSON simples — vira um segredo próprio. Você revisa as chaves antes — os valores ficam ocultos — e o arquivo em si nunca é guardado.',
  },
  chooseFile: { en: 'Choose a .env or JSON file', pt: 'Escolher um arquivo .env ou JSON' },
  importSkipped: { en: '{n} entry(ies) were not KEY=value text and were ignored.', pt: '{n} item(ns) não eram CHAVE=valor em texto e foram ignorados.' },
  act_import: { en: 'Import', pt: 'Importar' },
  act_skip: { en: 'Skip', pt: 'Pular' },
  act_replace: { en: 'Replace (new version)', pt: 'Substituir (nova versão)' },
  act_rename: { en: 'Import with another name', pt: 'Importar com outro nome' },
  clash: { en: 'already exists', pt: 'já existe' },
  emptyValue: { en: 'empty', pt: 'vazio' },
  importInto: { en: 'Into group', pt: 'No grupo' },
  importGo: { en: 'Import', pt: 'Importar' },
  importDone: { en: '{c} created, {r} replaced, {s} skipped.', pt: '{c} criados, {r} substituídos, {s} pulados.' },
  groupName: { en: 'Group name (a folder, a repo, a project…)', pt: 'Nome do grupo (uma pasta, um repositório, um projeto…)' },
  rename: { en: 'Rename', pt: 'Renomear' },
  deleteGroup: { en: 'Delete group', pt: 'Apagar grupo' },
  deleteGroupNote: { en: 'Its secrets are kept and move out of the group.', pt: 'Os segredos dele são mantidos e saem do grupo.' },
  items: { en: '{n} secret(s)', pt: '{n} segredo(s)' },
  network: { en: 'Could not reach agentop on this computer.', pt: 'Não foi possível falar com o agentop neste computador.' },
  neverPaste: { en: 'Agentistics never asks you to paste a secret into a chat.', pt: 'O Agentistics nunca pede para você colar um segredo num chat.' },
  backupNote: {
    en: 'Backups keep older encrypted copies of your vault; they are erased by themselves after a key change, or now, with this button.',
    pt: 'Os backups guardam cópias criptografadas antigas do seu cofre; elas são apagadas sozinhas depois de uma troca de chave, ou agora, por este botão.',
  },
  backupWipe: { en: 'Erase the vault\'s history in the backup', pt: 'Apagar o histórico do cofre no backup' },
  backupWipeConfirm: {
    en: 'Erase the older vault copies from the GitHub backup? The newest stays; this cannot be undone. It asks for your code and Windows Hello.',
    pt: 'Apagar as cópias antigas do cofre do backup no GitHub? A mais nova fica; não dá para desfazer. Pede o seu código e o Windows Hello.',
  },
  backupWiped: { en: '{n} older vault copy(ies) erased from the backup.', pt: '{n} cópia(s) antiga(s) do cofre apagada(s) do backup.' },
  phoneTitle: { en: 'On your phone', pt: 'No celular' },
  phoneLockedRegister: {
    en: 'To use this phone: 1) open the vault on your computer, 2) reload this page and tap Register this phone, 3) approve on the computer.',
    pt: 'Para usar este celular: 1) abra o cofre no computador, 2) recarregue esta página e toque em Registrar este celular, 3) aprove no computador.',
  },
  phoneReload: { en: 'Reload', pt: 'Recarregar' },
  phoneInsecure: {
    en: 'To use your phone\'s fingerprint or face, open Agentistics by its https address — for example by turning on HTTPS certificates in your Tailscale network and using the machine\'s https name.',
    pt: 'Para usar a digital ou o rosto do celular, abra o Agentistics pelo endereço https — por exemplo ligando os certificados HTTPS na sua rede Tailscale e usando o nome https da máquina.',
  },
  phoneUnsupported: { en: 'This browser cannot use a passkey.', pt: 'Este navegador não consegue usar uma passkey.' },
  phoneReady: { en: 'This phone is registered: it opens the vault with its fingerprint or face plus your code, and seeing or changing a secret asks for its fingerprint again.', pt: 'Este celular está registrado: abre o cofre com a digital ou o rosto mais o seu código, e ver ou mudar um segredo pede a digital de novo.' },
  phoneRegisterWhy: {
    en: 'Register this phone so it can open the vault and see secrets with its own fingerprint or face. It asks your code here, then an approval with Windows Hello on the computer — once.',
    pt: 'Registre este celular para ele abrir o cofre e ver segredos com a própria digital ou rosto. Pede o seu código aqui e depois uma aprovação com o Windows Hello no computador — uma vez só.',
  },

  phoneRegister: { en: 'Register this phone\'s fingerprint', pt: 'Registrar a digital deste celular' },
  phoneLabel: { en: 'Phone', pt: 'Celular' },
  phoneApproveOnPc: { en: 'Approve it in Windows Hello on the computer…', pt: 'Aprove no Windows Hello do computador…' },
  phoneCodeOn: { en: 'The computer also accepts your code here: a fresh code opens 30 seconds to see secrets.', pt: 'O computador também aceita o seu código aqui: um código novo abre 30 segundos para ver segredos.' },
  phoneDesktopIntro: {
    en: 'Phones that can open the vault and its secrets. A phone registers from the phone itself: it asks your code there, and a request appears here for you to approve with Windows Hello. Windows Hello is never asked from a phone.',
    pt: 'Celulares que podem abrir o cofre e os segredos. Um celular se registra pelo próprio celular: ele pede o seu código lá, e aparece um pedido aqui para você aprovar com o Windows Hello. O Windows Hello nunca é pedido a partir de um celular.',
  },

  phoneNone: { en: 'No phone registered yet.', pt: 'Nenhum celular registrado ainda.' },
  phoneRemove: { en: 'Remove', pt: 'Remover' },
  phoneCodeToggle: { en: 'Open the vault from the phone with the code alone (and see secrets for 30 s)', pt: 'Abrir o cofre pelo celular só com o código (e ver segredos por 30 s)' },
  phoneCodeCost: {
    en: 'Off by default. With it on, a phone you approved here once keeps a key of its own, and that phone plus your current code opens the vault (and shows secrets for 30 seconds) — no fingerprint. A code alone, on any other device, still opens nothing. Turning it off deletes every such key at once. Over plain http outside Tailscale the code travels unencrypted. Editing and deleting still need the phone\'s fingerprint.',
    pt: 'Desligado por padrão. Ligado, um celular que você aprovou aqui uma vez guarda uma chave própria, e esse celular mais o seu código atual abre o cofre (e mostra segredos por 30 segundos) — sem digital. Um código sozinho, em qualquer outro aparelho, continua não abrindo nada. Desligar apaga todas essas chaves de uma vez. Em http simples fora do Tailscale o código passa sem criptografia. Editar e apagar continuam pedindo a digital do celular.',
  },
  phoneDevices: { en: 'Phones that open with the code alone', pt: 'Celulares que abrem só com o código' },
  phoneStale: { en: '{n} phone key(s) stopped working when the vault changed its key; those phones must be approved again.', pt: '{n} chave(s) de celular pararam de funcionar quando o cofre trocou de chave; esses celulares precisam ser aprovados de novo.' },
  phoneStaleClear: { en: 'Clear them', pt: 'Limpar' },
  phonePasskeys: { en: 'Phones with biometrics', pt: 'Celulares com digital' },
  // The FAB's quick vault (right-click / long-press on the chat button).
  fabOpen: { en: 'Open the vault', pt: 'Abrir o cofre' },
  quickTitle: { en: 'Vault', pt: 'Cofre' },
  // The quick views (Nay Cofre tab, header/FAB popover) never list every secret — the whole list lives on /vault.
  quickAll: { en: 'See the full list of your secrets here', pt: 'Veja a listagem dos seus segredos aqui' },
  quickAllHint: { en: 'Open the vault page with every secret, groups, trash and versions.', pt: 'Abre a página do Cofre com todos os segredos, grupos, lixeira e versões.' },
  // VAULT.UX-R2 — "só uso" (write-only), the one list, the code stage.
  useOnly: { en: 'Use only', pt: 'Só uso' },
  useOnlyHelp: { en: 'Sessions and providers can use it, but nobody can see or copy the value — not even you. This cannot be undone: to change it later, replace the value.', pt: 'Sessões e provedores podem usar, mas ninguém pode ver ou copiar o valor — nem você. Não dá para desfazer: para trocar depois, substitua o valor.' },
  useOnlySealed: { en: 'Use only — nobody can see or copy this value. You can replace it.', pt: 'Só uso — ninguém pode ver ou copiar este valor. Você pode substituí-lo.' },
  useOnlyBadge: { en: 'use only', pt: 'só uso' },
  replaceValue: { en: 'Replace value', pt: 'Substituir valor' },
  replaceTitle: { en: 'Replace the value', pt: 'Substituir o valor' },
  f_newValue: { en: 'Leave empty to keep the current value — it is never shown.', pt: 'Deixe vazio para manter o valor atual — ele nunca é mostrado.' },
  section_all: { en: 'All', pt: 'Todos' },
  section_mine: { en: 'Yours', pt: 'Seus' },
  section_system: { en: 'System', pt: 'Do sistema' },
  systemNote: { en: 'Kept by Agentistics itself (backups, the central, the encrypted channel). Only the name, file, date and state are shown — never a value.', pt: 'Guardados pelo próprio Agentistics (backups, a central, o canal cifrado). Só aparecem nome, arquivo, data e estado — nunca o valor.' },
  systemEmpty: { en: 'Agentistics keeps no secret of its own on this machine yet.', pt: 'O Agentistics ainda não guarda nenhum segredo próprio nesta máquina.' },
  systemBadge: { en: 'system', pt: 'sistema' },
  codeStageTitle: { en: 'Confirm it is you', pt: 'Confirme que é você' },
  codeStageSub: { en: 'Type the 6 digits from your authenticator app to see the list.', pt: 'Digite os 6 dígitos do seu app autenticador para ver a lista.' },
  quickClose: { en: 'Close', pt: 'Fechar' },
  // VAULT v4 (2026-10-06) — the one /vault page: a header, four tabs, rows of one line each.
  pageIntro: { en: 'Your secrets and the ways you confirm actions, in one place.', pt: 'Seus segredos e formas de confirmar ações, em um só lugar.' },
  areasLabel: { en: 'Vault areas', pt: 'Áreas do cofre' },
  tab_secrets: { en: 'Secrets', pt: 'Segredos' },
  tab_methods: { en: 'Unlock methods', pt: 'Métodos de desbloqueio' },
  tab_devices: { en: 'Devices', pt: 'Dispositivos' },
  tab_settings: { en: 'Settings', pt: 'Configurações' },
  area_secrets_d: { en: 'Keep what only you should see.', pt: 'Guarde o que só você deve ver.' },
  area_methods_d: { en: 'Choose how you confirm it is you.', pt: 'Escolha como confirmar que é você.' },
  area_devices_d: { en: 'Manage the devices that can confirm actions.', pt: 'Gerencie os dispositivos que podem confirmar ações.' },
  area_settings_d: { en: 'Adjust timing, recovery and backup.', pt: 'Ajuste tempo, recuperação e backup.' },
  importShort: { en: 'Import', pt: 'Importar' },
  f_search: { en: 'Search', pt: 'Buscar' },
  searchShort: { en: 'Name, group or tag', pt: 'Nome, grupo ou tag' },
  countLine: { en: '{n} secret(s) ({s} system)', pt: '{n} segredo(s) ({s} do sistema)' },
  learnMore: { en: 'Learn more', pt: 'Saiba mais' },
  learnUnlock: { en: 'Learn more about unlocking', pt: 'Saiba mais sobre desbloqueio' },
  learnProtect: { en: 'Learn more about protection', pt: 'Saiba mais sobre proteção' },
  moreActions: { en: 'More actions', pt: 'Mais ações' },
  moveTo: { en: 'Move to group', pt: 'Mover para grupo' },
  systemMeta: { en: 'System', pt: 'Sistema' },
  sealedOn: { en: 'sealed on {date}', pt: 'cifrado em {date}' },
  details: { en: 'Details', pt: 'Detalhes' },
  tabCreate: { en: 'Create', pt: 'Criar' },
  tabImport: { en: 'Import .env / JSON', pt: 'Importar .env / JSON' },
  useOnlyShort: { en: 'Sessions use the value; nobody sees or copies it (cannot be undone)', pt: 'Sessões usam o valor, ninguém vê nem copia (não dá para desfazer)' },
  moreOptions: { en: 'More options', pt: 'Mais opções' },
  saveSecret: { en: 'Save secret', pt: 'Salvar segredo' },
  manageGroups: { en: 'Manage groups', pt: 'Gerenciar grupos' },
  st_active: { en: 'active', pt: 'ativo' },
  st_off: { en: 'off', pt: 'desligado' },
  st_soon: { en: 'coming soon', pt: 'em breve' },
  st_paused: { en: 'paused', pt: 'pausado' },
  st_frozen: { en: 'blocked', pt: 'bloqueado' },
  st_trusted: { en: 'trusted', pt: 'confiável' },
  st_missing: { en: 'not set up', pt: 'não configurado' },
  st_open: { en: 'open', pt: 'aberto' },
  m_hello_d: { en: 'This computer · biometrics or PIN', pt: 'Este PC · biometria ou PIN' },
  m_key: { en: 'Security key', pt: 'Chave de segurança' },
  m_key_d: { en: 'A USB or NFC key', pt: 'Uma chave USB ou NFC' },
  m_passkey: { en: 'Passkey / phone biometrics', pt: 'Passkey / digital do celular' },
  m_passkey_d: { en: '{n} phone(s) with biometrics', pt: '{n} celular(es) com digital' },
  m_passkey_none: { en: 'No phone with biometrics yet', pt: 'Nenhum celular com digital ainda' },
  m_code: { en: 'Authenticator code', pt: 'Código do autenticador' },
  m_code_d: { en: '6-digit code · last used {date}', pt: 'Código de 6 dígitos · último uso {date}' },
  m_code_none: { en: '6-digit code from an authenticator app', pt: 'Código de 6 dígitos de um app autenticador' },
  manage: { en: 'Manage', pt: 'Gerenciar' },
  activate: { en: 'Turn on', pt: 'Ativar' },
  change: { en: 'Change', pt: 'Alterar' },
  setupNow: { en: 'Set up', pt: 'Configurar' },
  dev_thisPc: { en: 'This computer', pt: 'Este PC' },
  dev_thisPc_d: { en: 'In use now · opens the vault here', pt: 'Usado agora · abre o cofre aqui' },
  dev_thisPhone: { en: 'This phone', pt: 'Este celular' },
  dev_passkey_d: { en: 'Biometrics · {rp}', pt: 'Digital · {rp}' },
  dev_device_d: { en: 'Opens with the code alone', pt: 'Abre só com o código' },
  addPhone: { en: 'Add a phone', pt: 'Adicionar telefone' },
  codeOnPhone: { en: 'Accept the code on the phone', pt: 'Aceitar código no celular' },
  codeOnPhone_d: { en: 'An approved phone opens the vault with the code alone.', pt: 'Um celular aprovado abre o cofre só com o código.' },
  set_state: { en: 'Vault open', pt: 'Cofre aberto' },
  set_state_d: { en: 'Locks by itself in {n} min', pt: 'Tranca sozinho em {n} min' },
  set_autolock_d: { en: 'Lock after {n} minutes without use', pt: 'Trancar após {n} minutos sem uso' },
  set_backup: { en: 'Backup', pt: 'Backup' },
  set_backup_d: { en: 'Encrypted copies of the vault in your backup.', pt: 'Cópias criptografadas do cofre no seu backup.' },
  openBackup: { en: 'Open backup', pt: 'Abrir backup' },
  danger: { en: 'Danger zone', pt: 'Zona de perigo' },
  danger_d: { en: 'Erase the older vault copies kept in the backup.', pt: 'Apagar as cópias antigas do cofre guardadas no backup.' },
  dangerBtn: { en: 'Erase history', pt: 'Apagar histórico' },
  rec_new_short: { en: 'Make a new one', pt: 'Gerar nova' },
  rec_new_d: { en: 'a new one replaces it', pt: 'uma nova substitui a atual' },
  rec_recover_short: { en: 'Recover', pt: 'Recuperar' },
  rec_recover_d: { en: 'Lost your phone and Windows Hello? On this computer only.', pt: 'Perdeu o celular e o Windows Hello? Só neste computador.' },
  namePh: { en: 'e.g. Production API', pt: 'Ex.: API de produção' },
  valuePh: { en: 'Protected value', pt: 'Valor protegido' },
  f_tagsShort: { en: 'Tags', pt: 'Tags' },
  tagsPh: { en: 'production, api', pt: 'produção, api' },
  removeTitle: { en: 'Remove "{name}"?', pt: 'Remover "{name}"?' },
  removePhoneMsg: { en: 'This phone stops opening the vault. To use it again, register it again.', pt: 'Este celular deixa de abrir o cofre. Para usar de novo, registre-o outra vez.' },

} as const satisfies Record<string, Pair>

export type PKey = keyof typeof PERSONAL_TEXT
export function pt_(k: PKey, lang: PLang, vars: Record<string, string | number> = {}): string {
  return PERSONAL_TEXT[k][lang].replace(/\{(\w+)\}/g, (_, v: string) => String(vars[v] ?? `{${v}}`))
}
