#!/usr/bin/env bun
/**
 * engine-slot.ts — writes `server/engine-slot.generated.ts`, the ONE place the host names an engine.
 *
 * `bun build --compile` resolves every import at bundle time, before dead-code elimination (the
 * `react-devtools-core` stub in packages/tui/stubs exists for exactly this), so an engine cannot be
 * an optional `import()` — a build without one would not compile. The slot is generated instead,
 * the `embedded-dist.generated.ts` pattern, and is gitignored for the same reason.
 *
 * What it exports is decided here, in this order:
 *
 *   --null (or AGENTISTICS_ENGINE_SLOT=null) → `createEngine = null`: the COMMUNITY build.
 *   AGENTISTICS_ENGINE_DIR                     → that checkout's engine entry.
 *   packages/engine/ beside the others         → `@agentistics/engine`.
 *   server/engine/in-tree.ts present           → the engine code that still lives in this tree
 *                                                (the migration's transitional state; the file goes
 *                                                when the code moves, and this branch goes with it).
 *   nothing                                    → the null slot.
 *
 * `--if-missing` leaves an existing slot alone — what `bun run stub` uses, so a fresh checkout
 * typechecks and a slot somebody generated on purpose is not overwritten behind them.
 */
import { existsSync, writeFileSync } from 'node:fs'
import { join, relative, resolve } from 'node:path'

const SERVER_PKG = new URL('..', import.meta.url).pathname
const ROOT = resolve(SERVER_PKG, '..', '..')
export const SLOT_PATH = join(SERVER_PKG, 'server', 'engine-slot.generated.ts')

export type SlotSource =
  | { kind: 'null' }
  | { kind: 'dir'; dir: string }
  | { kind: 'package' }
  | { kind: 'in-tree' }

/** PURE. Which engine this build gets. */
export function chooseSlot(o: {
  nullRequested: boolean
  engineDir: string | undefined
  packageExists: boolean
  inTreeExists: boolean
}): SlotSource {
  if (o.nullRequested) return { kind: 'null' }
  if (o.engineDir && o.engineDir.trim() !== '') return { kind: 'dir', dir: o.engineDir }
  if (o.packageExists) return { kind: 'package' }
  if (o.inTreeExists) return { kind: 'in-tree' }
  return { kind: 'null' }
}

const HEADER = [
  '// GENERATED by packages/server/scripts/engine-slot.ts — do not edit, do not commit.',
  "import type { CreateEngine } from '@agentistics/engine-api'",
  "import type { AgentisticsEvent } from '@agentistics/core'",
]

/** PURE. The slot file's text. `slotDir` is where the file lives, for a relative engine path. */
export function renderSlot(src: SlotSource, slotDir: string): string {
  const lines = [...HEADER]
  switch (src.kind) {
    case 'null':
      lines.push(
        '/** No engine: the community build. */',
        'export const createEngine: CreateEngine<AgentisticsEvent> | null = null',
        "export const engineSlot = 'null' as const",
      )
      break
    case 'dir': {
      let rel = relative(slotDir, resolve(src.dir)).split('\\').join('/')
      if (!rel.startsWith('.')) rel = `./${rel}`
      lines.push(
        `import { createEngine as create } from '${rel}'`,
        'export const createEngine: CreateEngine<AgentisticsEvent> | null = create as CreateEngine<AgentisticsEvent>',
        "export const engineSlot = 'dir' as const",
      )
      break
    }
    case 'package':
      lines.push(
        "import { createEngine as create } from '@agentistics/engine'",
        'export const createEngine: CreateEngine<AgentisticsEvent> | null = create as CreateEngine<AgentisticsEvent>',
        "export const engineSlot = 'package' as const",
      )
      break
    case 'in-tree':
      lines.push(
        "import { createEngine as create } from './engine/in-tree'",
        'export const createEngine: CreateEngine<AgentisticsEvent> | null = create',
        "export const engineSlot = 'in-tree' as const",
      )
      break
  }
  return lines.join('\n') + '\n'
}

if (import.meta.main) {
  const argv = process.argv.slice(2)
  if (argv.includes('--if-missing') && existsSync(SLOT_PATH)) process.exit(0)
  const src = chooseSlot({
    nullRequested: argv.includes('--null') || process.env.AGENTISTICS_ENGINE_SLOT === 'null',
    engineDir: process.env.AGENTISTICS_ENGINE_DIR,
    packageExists: existsSync(join(ROOT, 'packages', 'engine', 'package.json')),
    inTreeExists: existsSync(join(SERVER_PKG, 'server', 'engine', 'in-tree.ts')),
  })
  writeFileSync(SLOT_PATH, renderSlot(src, join(SERVER_PKG, 'server')))
  process.stdout.write(`engine slot: ${src.kind}${src.kind === 'dir' ? ` (${src.dir})` : ''} → packages/server/server/engine-slot.generated.ts\n`)
}
